### ISSUE TITLE
Sample to get started with bezier 

### ISSUE THREAD

**Issue by safoora** [Pomax/bezierjs#107]
Can I get an example to use this library in node.I am having trouble to start off with.
I am looking for offsets.

**Comment by Pomax** [comment]
Did the example code for https://pomax.github.io/bezierjs/#offset not offer enough to get you started? Both examples show the constructor, and the offset call, and then how to iterate through the result.

**Comment by paramecie** [comment]
Same here, dear Pomax - very sorry to be such a newbie :-(

I've node 10x working on Windows developping a js application in p5.js (Processing), it works fine.

I ran npm -install -g bezier-js, no error.

Apparently your files have been installed in:
C:\Users\[Myself]\AppData\Roaming\npm\node_modules\bezier-js

On my local dev folder on drive D:\something\... I copied your /lib folder to a local /libraries/bezier one, where there are the 5 files:
bezier, normalise-svg, poly-bezier, svg-to-beziers, utils (all are .js)

I've added in index.html:
<script language="javascript" type="text/javascript" src="libraries/bezier/bezier.js"></script>
I use /libraries file because it's just historical - I've there my ps5.js library, and it works well.

Visual Studio code properly highlights the syntax and sees your library apparently.

I wrote a test.js with a simple test, this is in Draw():
var curve = new Bezier(150,40 , 80,30 , 105,150);
drawSkeleton(curve);
drawCurve(curve);

I put some other code to show lines and such on canvas, it works well (before those lines).

I use browser-sync to open the page on localhost:3000

On my firefox console, it says:
ReferenceError: require is not defined
showing bezier.js:24:7 var utils = require("./utils.js");

It also logs:
ReferenceError: Bezier is not defined
showing: var curve = new Bezier(150,40 , 80,30 , 105,150);

It's not working :-(
VERY sorry again and a big thanks for this huge work you've done, really hoping I can make it run here.

**Comment by Pomax** [comment]
The _only_ thing functions that Bezier.js gives you is the functions listed in the API documentation. In the example source `drawSkeleton` and `drawCurve` are helper code that has nothing to do with Bezier.js and just means the source doesn't have to repeat itself a million times. 

If you want to know how to implement your own `drawSkeleton` and `drawCurve` etc, look at https://github.com/Pomax/bezierjs/blob/gh-pages/js/draw.js for inspiration.

**Comment by paramecie** [comment]
Hi. Thanks! Sorry if I don't how it works with node, npm, dev environment and package.json :-(
I also didn't know drawSkeleton wasn't an API function, I just read your page/code sample.
OK, I'm trying what you said now.
Thanks again.

**Comment by paramecie** [comment]
I've moved bezier.js to my /libraries folder.

I have in index.html:
<script language="javascript" type="text/javascript" src="libraries/p5.js"></script>
<script language="javascript" type="text/javascript" src="libraries/bezier.js"></script>

In my Draw() function I have other working code (or none, I tested) and:
var curve = new Bezier(150,40 , 80,30 , 105,150);

I still have the same errors, "require is not defined" and Bezier the same, see print screen:
https://snag.gy/1gl2z9.jpg

I don't get it about docs: how can I write an equivalent of drawCurve; should I read the whole lib to draw a curve?

**Comment by Pomax** [comment]
Then you did _not_ copy the right file because as we can see from https://raw.githubusercontent.com/Pomax/bezierjs/gh-pages/bezier.js there isn't a single instance of the word "require" in there...

**Comment by paramecie** [comment]
Wow thanks, that did it: I downloaded the compressed version and put it in Libraries folder, et voilà, as we say here :-)

I previously copied the bezier.js from the npm folder, this is why it had the require code...

Yes I know about the canvas2D, I already tried the bezier and drew a few, but it has limited functionnalities. Your lib helper draw.js is very fine, I'll figure out the remaining, don't worry.

So, thanks a bunch, happy to have talked to the real Pomax himself - and season greetings!

**Comment by paramecie** [comment]
I successfully wrote the drawCurve() function in processing ps5.js. Thanks again!

A question... hoping I don't bother.

I want a bezier from the start (0,0, but not always), to another border (here the bottom one).
And it should intersect, at least approximately) with a point in between: the orange point on the screen shot:
https://snag.gy/PwbJzI.jpg

A ballistic trajectory that aims a target, but can go through or miss the target).

Solutions:

I can set a bezier from the start to the orange point, no problem - but then, I didn't find yet a way to make the same curve longer, to go down to the bottom...

Or I can set a bezier from start to bottom, and loop a hundred "grasp points" in the middle, until I find an (approx) intersection with the orange dot...

I was also thinking calculating 2 beziers, one down to the orange point, and one to the bottom - but how to make them approx identical in their curve?

Thanks if you've any experience or idea?

**Comment by Pomax** [comment]
Use http://pomax.github.io/bezierjs/#fromPoints ?

**Comment by paramecie** [comment]
Wow how could I missed this function :-(

I tried. Yes, tuning t and also the bottom point is a bit difficult... Hoping I can resolve this.

Apart this, I'm puzzled by this notation that I don't know, example: {x:0, y:0}
I'm learning js through ps5.js, and am used to use Vectors.

There are some strange behaviours in the library:

* with: var curve = new Bezier(0,0 , 700,100, 900,350); the library works well, and understands them as couple of coordinates

* but with Bezier.quadraticFromPoints I can't put couples of coordinates, I've to use {x:0, y:0}

* much more, I can replace the SECOND parameter with a Vector, see code below - but if I replace the first parameter, the curve is crazy (out of screen), see the commented code line which doesn't work:

`       

        let p1=createVector(0,0);

        let p2=createVector(target.x,target.y);

        // p2 successfully replaced by a Vector
        var curve= new Bezier.quadraticFromPoints({x:0, y:0}, p2, {x:target.x, y:bottom}, 0.6);

        // but in this case, the curve goes wild!
        // var curve= new Bezier.quadraticFromPoints(p1, p2, {x:target.x, y:bottom}, 0.6);
`

Again - very sorry if I missed something.

**Comment by Pomax** [comment]
I would recommend against learning JS "through p5js". If you're learning p5js, you're learning a specific API, not the JS programming language. And that's fine, but if you don't learn JS "as JS" on the side, you'll keep running into this. I don't want to drag this issue on: I'm not a support agent for your code, so I'll say this:

`{ x: ..., y: ... }` is just [standard JS notation](https://developer.mozilla.org/en-US/docs/Learn/JavaScript/Objects/Basics) for an object with two properties, `x` and `y`. This library, which is a plain JS library, takes those kind of objects in a lot of places, so read through the API documentation to see when and where it does.

For convenience, the constructor `new Bezier(...)` allows you to call it with several signatures, including "plain numbers" (either 6 or 8) as well as the move proper "array of coordinate objects", so your `new Bezier(0,0 , 700,100, 900,350);` can also be written as `new Bezier([ {x:0,y:0}, {x:700,y:100}, {x:900,y:350} ]);` (and is how I would advise you to use it).

The `quadraticFromPoints` function does NOT have that convenience: if you look at [its API documentation](http://pomax.github.io/bezierjs/#fromPoints) you will see it says that it **must** be called with four arguments of which the first three **must** be coordinate objects with x/y properties, and the fourth argument must be a numeric value between 0 and 1 (inclusive on both).

**Comment by paramecie** [comment]
Hi!

Thanks for your time and reply.
I'm more aware of standard JS and p5.js differences, worked and learned a lot all about those.
In short, my question may have appeared a bit silly, or newbie at least.

Right now what I should do (but I've too few time) is a p5.js library that 'encapsulates' your pure js lib.

That would be very fine for people wanting to quick rad or art makers that often use P5 for its convenience - to be able to use beziers.js in a more casual way, or anyway the P5 way...

**If not me - please someone here make it: that would really be a wonderful addition to P5!**

Thanks always Pomax - wishing you a fine Christmas!

**Comment by Pomax** [comment]
P5js _is JS_ and so doesn't need js libraries "wrapped". It is itself plain JS, just with its own API, so all a wrapper would do is waste cpu cycles. Just call this library with the correct function signatures, which P5js lets you do just fine.

That's also part of "learning to program": understanding that different frameworks can work together just fine, as long as you follow their interfaces. Just because you use p5js does not mean every library you want to use should follow "the p5js way". That is, in fact, the complete opposite of what you should be learning here. You should be learning that different methodologies can work together just fine, as long as you follow their methodologies where appropriate, instead of trying to fight them in an effort to make things be what they aren't.

A merry christmas to you, too, and happy coding.
