### ISSUE TITLE
Remove circular dependency when bundling with rollup

### ISSUE THREAD

**Issue by tim-kilian** [Pomax/bezierjs#112]
Rollup is reporting a warning when compiling I am trying to build my production environment.

```(!) Circular dependency: node_modules\bezier-js\lib\bezier.js -> node_modules\bezier-js\lib\utils.js -> node_modules\bezier-js\lib\bezier.js```

**Comment by Pomax** [comment]
Tell rollup not to try rolling - there is a circular dependency because Bezier objects rely on utils for core utility functions, and utils has to build Bezier objects as a result of some of those. However, this is a _mutual_ dependency, not a circular one (it's not a class hierarchy) and if rollup gets stuck on those, then that's probably worth filing on the rollup issue tracker, since there is nothing about that relationship that should be impossible to resolve.
