### ISSUE TITLE
Move to ES6

### ISSUE THREAD

**Issue by SukantPal** [Pomax/bezierjs#127]
Are there plans to modernize the codebase, to probably encourage more development? I could make a quick PR for you @Pomax

**Comment by Pomax** [comment]
Quick PRs tend to just be "ES6ish" in that they're broad stroke replacements that use the new syntax, but don't actually involve significantly rewriting code to take advantage of the patterns that ES2015-ES2020 enables, compared to ES5, so I'd rather not have a "quick PR" and would much more prefer a proper rewrite =)

Having said that, I would love to modernize it, and am currently focused on reworking the Primer's codebase, writing a custom element for the on-page graphics so I can replace the React code that exists for that, to turn it back into a true (but modern) HTML page.

If you want to get a head start on me getting to bezier.js, by all means have at it!

**Comment by Pomax** [comment]
Based on musings in #128:

If bezier.js gets uplifted to ES6, then that should be fully committed to: no more `require`, nothing that generates ES5, and ES5 code patterns that have been replaced with better ones in ES6, replaced with those better ones. Also, for linting, let's use https://prettier.io, without any customization: whatever it considers good code is simply what the code will look like (and that can change from version to version, but that's fine).

Let's do this in small, easy to PR, easy to review, and easy to land steps:

1. let's start a new `es6` branch (done!), with just the `/lib` code and the old test file, and uplift those first, with an npm script for linting via `prettier`.
   1. initial super-minimal rewrites just so that things use `import`/`export` without _any_ other code changes
   2. then, switch things over to normal modern class syntax, without _any_ code changes inside functions
   3. then, start rewriting function internals to ES6 syntax and patterns.
2. switch the testing to `jest`, because it's still the weird ancient hand-written testing atm.
3. once that work's done, let's add in rollup so that a browser "bundle" can be created. Note that minifcation is not necessary here: any sane server is going to serve that file with gzip, which is superior to any kind of JS based minification solution out there, and can actually perform worse on pre-minified code.

**Comment by Pomax** [comment]
I will probably do some work on this tomorrow (Friday, August 7) too, since I've reached the point in my rewrite of the Bezier Primer that it _needs_ an ES6 version of Bezier.js for all the examples to actually work.

**Comment by Pomax** [comment]
I've finished step 2 and will be working on step 3.

**Comment by Pomax** [comment]
I've finished step 3 and will be working on step 4.

Once that's done, we'll be ready to tackle the real "meat and potatoes" of this issue: auditing, writing tests for, and (hopefully) modernizing the code for every single function.

**Comment by Pomax** [comment]
step 4 down, I'll get step 5 out of the way and then probably stop for a bit because step 6 is just going to be a lot of PRs =)

**Comment by Pomax** [comment]
turns out Jest has some issues with detecting module code, so that's not quite as much of a drop-in as I'd hoped...

**Comment by Pomax** [comment]
Steps 5 and 6 done, so I'm going to (literally =) call it a day and will probably let this sit for a few days now that I can use bezier.js as an ES module (albeit not a "done" es module) for the purposes of redoing the Primer tech stack and sketch code.

**Comment by SukantPal** [comment]
@Pomax I'll start step 7 this weekend ;)

**Comment by Pomax** [comment]
ES6 deployed.
