### ISSUE TITLE
Lighten npm package

### ISSUE THREAD

**Issue by JeremiePat** [Pomax/bezierjs#130]
Currently the Bezier.js npm package embed the whole git repository, which includes a lot of unnecessary files. It would be nice if the npm package could be slightly optimize to avoid unnecessary network overhead (ok, I realize I'm being annoying for a couple of ko, but I'm okay to commit myself to do the necessary work).

A simple [`.npmignore` file](https://docs.npmjs.com/configuring-npm/package-json.html#files) at the root of the repository will do the trick to list everything that shouldn't be included into the npm package.

Optionally, I would suggest to also move all things related to the documentation under a `/docs` folder (which will make documentation maintenance and improvement easier while making it easier to exclude from the npm package). However this will ask for some github configuration to keep a nice [pomax.github.io/bezierjs](https://pomax.github.io/bezierjs) page).

**Comment by Pomax** [comment]
I absolute hate github's insistence that your gh-pages are either the root, or the `docs` folder, so that's not happening.  However, adding an .npmignore so that only the relevant files get packed up is perfectly fine - I'm currently far too busy with first getting the Primer on Bezier curves completely rewritten in terms of tech stack (8 weeks in and counting) so if you want to get a head start on this by filing a PR for one (remembering that if there's an `.npmignore`, the `.gitignore` file does nothing as far as NPM goes) then that'll probably get things sorted out sooner than if folks will be waiting for me to finish up the Primer work.

**Comment by JeremiePat** [comment]
PR #131 done.

I didn't add the files within the `.gitignore` just because NPM already ignore them.
I'm looking forward for the v2 of the Primer, so don't waste time with nit-picking stuff like an `.npmignore` file 😝

**Comment by Pomax** [comment]
folded into the ES6 deploy, now on npm as v3.0.1
