### ISSUE TITLE
How to merge bezier curve

### ISSUE THREAD

**Issue by ArvinTung** [Pomax/bezierjs#151]
First of all thanks for that library
How can I merge several bezier curve，in another word, the revert function of reduce()
for example, I reduced a curve A using 'reduce' to B, C, D, how can I get the combine curve A ?

**Comment by Pomax** [comment]
Unfortunately, while splitting up curves is easy, merging them is a non-trivially hard task, so I've simply not written any code to achieve that yet. The theory behind it is also still a section that I have yet to write for https://pomax.github.io/bezierinfo

@raphlinus did some investigations for C shaped curves over on https://raphlinus.github.io/curves/2021/03/11/bezier-fitting.html recently that you might (or might not) find interesting this in space.

**Comment by raphlinus** [comment]
FWIW, the method in that post should work for all Beziers, not just C-shaped ones. This is something that's probably unclear about my wording, because the C-shaped ones are definitely more *interesting* for admitting multiple solutions that have to be disambiguated some other way (generally by directly comparing an error metric against the source curve).

**Comment by ArvinTung** [comment]
Thanks a lot, but it's too difficult  for me

I wonder if there have an simpler way for my situation

I got several curves, for example, B, C and D，and I know they are reduced from A using the 'reduce' function, then I want to got A

**Comment by Pomax** [comment]
In that case, why would you ever need code to "try to merge them" rather than just making each section aware what its original curve was? E.g.:
```js
const curve = new Bezier(...);
const segments = curve.reduce();
segments.forEach(s => s.original_curve = curve);
```
No need to compute anything, just directly look up the original curve and you're done?
```

**Comment by ArvinTung** [comment]
I know `segments` are reduced by a curve, but I don't know what the curve is, so I want to get the origin curve from `segments`
I wonder is there any simpler way for this situation, I'm not sure but I think maybe it's easier than curve fitting ?

**Comment by anthrotype** [comment]
If you know the two cubic bezier curves were split from a single cubic bezier curve, you can perform something like a reverse De Castelieau algorithm to retrive the original curve. See https://math.stackexchange.com/a/879213
I implemented that in https://github.com/googlefonts/cu2qu/pull/29 (though I never finished that PR)

```python
def merge_cubic_beziers(points):
    """ Return the initial cubic bezier curve subdivided in two segments.

    Input must be a sequence of 7 points (tuple or complex), comprising
    two consecutive cubic curve segments sharing the middle point.
    Inspired by an answer on math.stackexchange.com:
    https://math.stackexchange.com/a/879213
    """
    if len(points) != 7:
        raise ValueError("Expected 7 points, found {len(points)}")
    if isinstance(points[0], tuple):
        p1, p2, p3, p4, p5, p6, p7 = (complex(x, y) for (x, y) in points)
    k = abs(p5 - p4) / abs(p4 - p3)
    off1 = (1 + k) * p2 - k * p1
    off2 = ((1 + k) * p6 - p7) / k
    return [(v.real, v.imag) for v in (p1, off1, off2, p7)]
```

**Comment by Pomax** [comment]
On a programming note, if you "know the segments are reductions of the same curve", but you don't actually have that curve at hand, then you _don't know_ that your segments are reductions of the same curve. Instead, you'll have written code that _assumes_ that is true, and that's potentially very buggy. 

That said, yes, if you can somehow guarantee that the segments are all from the same original curve, then the reconstruction is pretty trivial: you can iteratively merge the segments because you have all the information required already encoded in the segments:

![image](https://user-images.githubusercontent.com/177243/114771318-44484280-9d21-11eb-8a95-ef5b325c0e45.png)

For every 2 segments you're merging, all we need to know is the `t` value, which is the ratio of `a` (the length of the first segment's end point to its associated control point) to `b` (the length of the second segment's start point to its associated control point). Now all you have to do is scale the control points along their tangents, to correct for their `t` value.

**Comment by Pomax** [comment]
I should add a short section on this to https://pomax,github.io/bezierinfo...

**Comment by ArvinTung** [comment]
very clear, thanks a lot, it helped me a lot
