### ISSUE TITLE
_bezierJs.default is not a constructor in codesandbox

### ISSUE THREAD

**Issue by mdiegoli** [Pomax/bezierjs#174]
Hi,
I'm using bezierjs, via npm, in a codesandbox project.
When I'm doing 

const curve = new Bezier(102, 33, 16, 99, 101, 129, 132, 173);

I have 

TypeError
_bezierJs.default is not a constructor.
I have to use a different class or something else?

This is the codesandbox link

https://codesandbox.io/s/modest-banzai-lv747?file=/src/index.js:6668-6730

Thank you

**Comment by mdiegoli** [comment]
This is the codesandbox

https://codesandbox.io/s/modest-banzai-lv747?file=/src/index.js:6668-6730

**Comment by Pomax** [comment]
Given that there is no `_bezierJs.default` in the code anywhere (neither the real code, which browsers can load just fine because it's modern ESM JS, nor the legacy CJS version), I don't think I'm the right person to ask about this. It sounds like npm is taking the already wrong version and then _further_ transpiling it for use in a browser.

**Comment by Pomax** [comment]
See if 6.1.0 now works for you. I added a `browser` field to the package.json so that hopefully nothing gets further transpiled.

**Comment by mdiegoli** [comment]
No, the problem still remain. Probably it's a codesandbox problem?

**Comment by mdiegoli** [comment]
Ok, it works on Codpen!
Many thanks

**Comment by Pomax** [comment]
I guess codesandbox runs transpiles even when it really shouldn't.
