### ISSUE TITLE
Why get(t = 0.5) point is not the middle point of the curve?

### ISSUE THREAD

**Issue by AJLoveChina** [Pomax/bezierjs#194]
Thanks for this library, and I am wondering why get(t=0.5) point is not located at the middle of the curve?  (the left part's length is not the same as the right part) 

![image](https://user-images.githubusercontent.com/11222746/221118002-f8c358af-7953-4bb3-940a-47e5458329a9.png)

Test on http://pomax.github.io/bezierjs/

**Comment by justvanrossum** [comment]
These sections from "the book" provide some insights:

- https://pomax.github.io/bezierinfo/#extended
- https://pomax.github.io/bezierinfo/#tracing

**Comment by Pomax** [comment]
tldr version: because `t` is the curve's computational input parameter, unrelated to distance along the curve.

**Comment by AJLoveChina** [comment]
thanks @justvanrossum @Pomax

**Comment by AJLoveChina** [comment]
hi @justvanrossum @Pomax , one more question : which api can get the middle point (by distance),  I tried but can't find this function.

Thanks :_)

**Comment by hfutrell** [comment]
I’d recommend using a guess-and-check approach (eg binary search) to find the midpoint. You can split the curve and then check the length of the sub curve, adjusting t until your sub curve has half the length of the original curve.Sent from my iPhoneOn Jul 6, 2023, at 7:17 PM, AJ ***@***.***> wrote:﻿
hi @justvanrossum @Pomax , one more question : which api can get the middle point (by distance),  I tried but can't find this function.
Thanks :_)

**Comment by Pomax** [comment]
You'd need the arc-length reparameterized version of the curve, which is _extremely_ not trivial, so the usual approach is to just binary search your way to victory: get the length of your curve, and set your target distance to half that. Then start with `t=0.5` and compute the arc length. If it's too high, pick `t -= 1/4`, if it's too low, pick `t += 1/4`. If those are too high, repeat but pick `t -= 1/8`, and if it's too low, pick `t += 1/8`. And then you keep repeating that with 1/16, 1/32, 1/64 etc. etc. until you're "close enough to your target distance".

Or, alternatively, you generate a LUT with an _approximated_ curve length (based on pixel distance rather than true arc length) and then you find the two points in that LUT that are closes to the total length divided by 2 and use a t value that's an interpolation of those two points.
