### ISSUE TITLE
Find optmal D1 - Bezier.cubicFromPoints

### ISSUE THREAD

**Issue by sysmaya** [Pomax/bezierjs#195]
I am developing an svg editor. And as part of the project, I require a function that finds the MINIMUM number of nodes to create an SVG path.
The idea is not to create a reduction, it is to recreate the shape (100% identical, if possible) but using the minimum number of nodes.

![b1](https://user-images.githubusercontent.com/18316343/228392917-112ed1a9-2d53-4ea1-aac6-fcd1bb19a32c.png)

I have created a function that iterates through the array of bezier points and finds those nodes.
The question is to find the optimal value of d1.
When I omit the value, the Bezier.cubicFromPoints function creates a value, which is almost perfect.
Doing manual tests I found that the optimal value is:
**Distance( P1, P2 ) /6**

In the attached image you can see that the nodes found do not allow degenerate curves to form. So the handles of the node should not be in remote positions, or deforming the curve too much.

I check the Bezier.js script and I see something like ABC, but I don't quite understand the concept.

**Comment by Pomax** [comment]
I'm not sure I understand what you're asking for, because it sounds like you're trying to implement curve fitting for arbitrary shapes, in which case: start at reading up on [potrace](https://en.wikipedia.org/wiki/Potrace) (read the PDF that is linked in the "further reading" section) and then branch out from there, because shape abstraction has lots of people implementing it in lots of different ways.
