### ISSUE TITLE
Diferences with the SVG getPointAtLength method

### ISSUE THREAD

**Issue by rveciana** [Pomax/bezierjs#48]
I'm trying to write a [simple library to get SVG paths properties](https://github.com/rveciana/path-properties/tree/master).
I'm using bezierjs for the Bezier curves, and it works ok with lengths, but with the position at certain point I find differences from the getPointAtLength method. 
![bezier](https://cloud.githubusercontent.com/assets/2832885/19832810/e3b9b1d4-9e2d-11e6-8a24-3403e0678f3e.png)
In this image you can see the points that should be the same, marked in different colors. [The functions called](http://geoexamples.com/path-properties/simple_test.html) are like:

     pathEl = d3.select("body").append("svg")
     .attr("width", 960)
     .attr("height", 300);
      path = pathEl
     .append("path")
     .attr("fill", "none")
     .attr("stroke", "black")
     .attr("d","M200,300 Q400,50 600,300");

     var curve = new Bezier(200,300,400,50,600,300);

     console.info("Bezier-js", curve.get(0.2));
     var browserLength = path.node().getTotalLength();
     console.info("SVG", path.node().getPointAtLength(0.2 * browserLength));

But the results are different:

    Bezier-js { x: 280.00000000000006, y: 220.00000000000003 }
    SVG { x: 267.53448486328125, y: 229.83480834960938 }

Am I doing something wrong? In bezierjs the length is given from 0 to 1, and in the SVG function, from 0 to the length of the curve, but the positions should be the same...
More curves with the same problem can be found [here](http://geoexamples.com/path-properties/).

**Comment by Pomax** [comment]
yes, [obviously](http://pomax.github.io/bezierinfo/#tracing) those are different points: `getPointAt(0.2)` means "get the point at `t=0.2`". That is nothing like what you're then computing after, because Bezier curves are **not lines**, so the notion that `t=0.2` is the same coordinate as `totalLength * 0.2` is completely invalid.

**Comment by Pomax** [comment]
Created a JSbin with your code, and modified it so it doesn't pretend what you're doing with bezierjs is even remotely the same as what you're doing in SVG: http://jsbin.com/fiyiyivefa/edit?js,output

Note that because bezier.js does not have a "get point at some distance" function, this is not a perfect match: we would have to find the point at `i-step/2` and at `i`, and then we would have to do a second check in side of that range to find the exact point `T` for which `curve.get(T)` yields the point at 20% distance along the curve.
