### ISSUE TITLE
[suggestion] Add .editorconfig and .eslint files

### ISSUE THREAD

**Issue by louisremi** [Pomax/bezierjs#54]
I'm in the process of writing a functional version of the lib, and I believe it would be great to have an .editorconfig and .eslint files to keep code consistent.
I can send a PR that adds those files and fix linting errors in the repo. Do you have an existing config you'd want to point me to, or an preferred config?

**Comment by Pomax** [comment]
I'm not a fan of "lots of dot-something files" - there are too many editors commonly used to justify a single format to be committed while leaving out the others, and this code will absolutely not lint unless you turn off almost every "decent practice" rule, because I wrote it for terseness mostly. The only important part I truly care about is that the code passes its tests.

**Comment by louisremi** [comment]
Ok. .editorconfig is compatible with a very large portion of editors out there (see http://editorconfig.org/#download), and I was ready to create a minimal eslint file and fix existing errors.
But this is your project. I hope you reconsider later.

**Comment by Pomax** [comment]
you can still file a PR for them, but then also make sure to update the package.json such that people *don't get* those files when they install bezier.js, so that they only exist for people explicitly work on the code. I'm curious what ESLint rules you can come up with. There's no bundling step so the JS code is written pretty tersely, and with plenty of exceptions to its own rules in order to stay reasonably compact.
