### ISSUE TITLE
make border of strokes with outline() function.

### ISSUE THREAD

**Issue by chengdu** [Pomax/bezierjs#56]
I want to make border ( i.e. outline) around the strokes of a character using bezierjs, but it can't work as expected. The output screenshot:
![screenshot](https://cloud.githubusercontent.com/assets/305967/20594899/dc696614-b272-11e6-8fb7-48837465c448.png)
Please refer here: http://jsbin.com/qicukorope
It even can't work with a very simple svg path e.g "M669 58L669 630", Bezier.fromSVG(d);
Any help will be great appreciate.

**Comment by Pomax** [comment]
Rather than (just) a zip file, can you show the code you're using in your post (or as follow-up comment) or as a jsbin link so that the code can be easily checked and interacted with by anyone who looks in on this issue tracker? The reduced example of what you're experiencing should not require all that much - just set up hardcoded list of the points you have (I assume these were abstracted with a RDP reduction while drawing　寸), and hardcoded the result of what comes out of any not-bezier-js code, so that the only real code that "does something" is the part where you feed points into bezier.js and ask it to do something for you.

Bezier.js doesn't do any curve fitting, for instance, so the image in your issue looks fine to me: it's a single curve, with what looks like a correct red outline (and some extra blue offset curves for visual debugging?)

**Comment by chengdu** [comment]
Okay, a page have be created for the test: http://jsbin.com/qicukorope

**Comment by Pomax** [comment]
Can you update that jsbin with a rawgit script instead of making lots of files in jsbin for each .js library? Because it looks like you made several jsbin files to act as script resources and then the JavaScript panel itself still has a huge file in it too, making it impossible to see the code you actually want to show (which, to ensure your script timings make sense, should be in that JS panel, not in the HTML source: don't put script code in your HTML, always load it with a script tag at the end of the DOM).

The following should work just fine in order to get the library included:
```
<script src="https://rawgit.com/Pomax/bezierjs/gh-pages/bezier.js"></script>
```

I'm happy to help figure this out, but I do need you to help me focus on "just the parts that go wrong": you have lots of code, almost none of it related or relevant to the problem. So, if I reduce your code to just importing bezier.js, and then *only* these lines:

```
var d = "M669 58L669 630L669 785C669 807.098 673.216 836.889 662.095 857C650.173 878.559 614.273 877.898 593 878.001C562.286 878.149 531.727 877.194 501 875.089C487.001 874.131 468.138 875.855 455 870.436C450.226 868.467 446.817 863.611 443 860.289C436.095 854.281 428.555 849.138 421 844M97 282L231 282L502 282L773 282L908 282M273 419C317.063 463.063 356.443 512.361 392.71 563C403.232 577.692 412.91 592.813 422.692 608C427.478 615.431 433.858 622.71 437 631";
var curve = Bezier.fromSVG(d);
var outline = curve.outline(25);
```

That's enough code to throw an error. When a minimal example is requested, really prune as much as you can because any code left in that isn't part of the problem, is a potential waste of time and effort in terms of seeing whether or not it's actually related to the problem. The above three lines, without any drawing code, and without any special HTML placeholder tags for content that will get slotted in later, is all we need to demonstrate this problem.

So with these three lines, we can see there are three possible problems that need investigation, instead of a million:

- [ ] is the SVG path malformed
- [ ] is the `fromSVG` function yielding a bad curve
- [ ] is there a bug somewhere in the  `outline()` code path.

**Comment by chengdu** [comment]
No, sir, it's really a bug.
even a very simple single bezier curve data e.g. "M702 -610L702 -826" can't work.

**Comment by Pomax** [comment]
I have no intention for Bezier.js to bei a general purpose pathing library. Please use something like Paper.js for that, it is easy to use and well written.
