### ISSUE TITLE
Question: how to find the t value that computes the halfway point on a bezier curve?

### ISSUE THREAD

**Issue by alexjlockwood** [Pomax/bezierjs#69]
This isn't an issue, but more of a question. Is there an easy way to use this library to find the t value that computes the point halfway along a bezier curve path? (i.e. the t value that splits the curve into two equal sized sub-curves)?

**Comment by deanmartinez** [comment]
I believe that would be 0.5, since t values are 0 to 1.

**Comment by Pomax** [comment]
What do you mean with "equal sized"? Equal arc length?

**Comment by alexjlockwood** [comment]
@deanmartinez Yeah, that's what I thought at first too... but @Pomax is right, `t = 0.5` only works for symmetric curves, which makes sense. Thanks so much for the in-depth answer! I was considering a binary search but wasn't sure if there was a more efficient alternative that I was missing. I guess there isn't. :P 

By equally sized, I did initially mean 'equal arc length'... but I wonder what is the difference between this and "taking up roughly the same amount of visual space"? Isn't arc length by definition the "visual length" of the curve?

BTW... thanks so much for your primer on bezier curves. Seriously, I have learned so much from it. :)

**Comment by alexjlockwood** [comment]
Hey @Pomax, thanks again for the response. But I think I actually found a case where your code breaks. When I run your code using the following input, it fails to find an input:

    findMidPointByDistance(new Bezier(5, 11, 5, 13, 5, 13, 5, 13))

Is there anything that can be done in these cases?

**Comment by Pomax** [comment]
yeah: check your curves to see if they're degenerate before applying algorithms intended for non-degenerate curves =)

In this particular case: "the curve has three coordinates in the same place: why is this a curve at all, your code should have turned this into a line segment."

**Comment by alexjlockwood** [comment]
@Pomax Fair point. Actually the thing I am working on is an SVG editor... and it isn't uncommon for programs like Adobe Illustrator to export commands like this unfortunately. But it should be easy enough to preprocess this stuff to get it in a more reasonable state.

Thanks again for your help!

**Comment by Pomax** [comment]
yeah, that's generally the idea - just because your editor is SVG doesn't mean your algorithms have to deal with the exact input you give them. Adding a "check if curve coming in is denegerate or not and pick a *much* simpler function to return instead" at the start of the `findMidPointByDistance()` function is pretty easy.

**Comment by alexjlockwood** [comment]
@Pomax Actually, I should probably ask... are there any other "degenerate" weird cases you could think of happening here? I did a search in your primer on bezier curves and didn't find anything on degenerate curves. Just wanted to make sure. :)

**Comment by Pomax** [comment]
That's a good point actually, filed https://github.com/Pomax/BezierInfo-2/issues/50 so that won't happen in the future. A degenerate curve is a "curve that is a not a curve", so specifically it is a curve of which all coordinates lie on the same line. So your curve is an example, but so is a curve `(1,1), (0,0), (3,3), (2,2)`, which has no repeated coordinates, but of which all coordinates lie on the line `y=x`. Because of discrete math, you typically end up having to do an alignment RT and then see if the control points are "near enough to y=0 to count as lining up". If so, this curve is a line, and if the control points are between start/end, it's simply a line (start)--(end), if the control points are outside that interval then you need to compute the extremities using the derivative (which works fine for any curve, not just non-degenerate ones) and then your line segment runs between those extremities.
